# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-25 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Con',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_list', models.CharField(max_length=500, verbose_name='事项内容')),
                ('flag', models.BooleanField(default=False, verbose_name='是否完成')),
                ('pubdate', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name_plural': '待办事项',
                'verbose_name': '待办事项',
            },
        ),
    ]
